spring:
  datasource:
    url: jdbc:mysql://localhost:3306/useservices
    username: root
    password: 542666
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  name: USER-SERVICE

server:
  port: 8081
