spring:
  datasource:
    url: jdbc:mysql://localhost:3306/useservices
    username: root
    password: 542666
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
#    show-sql: true   
#	 if you want to show sql commond so uncomment upper query
application:
  name: USER-SERVICE

server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
